server:
  port: 8080
spring:
  application:
    name: leaf
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username: root
    password:
  redis:
    host:
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  rabbitmq:
    host:
    port: 5672
    virtual-host: /
    username:
    password:
    listener:
      simple:
        prefetch: 1
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.leaf.entity # 别名扫描包
logging:
  level:
    com.leaf: debug
