server:
  port: 8081
spring:
  application:
    name: leaf
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/leaf?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username:
    password:
  redis:
    host:
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  rabbitmq:
    host:
    port: 5672
    virtual-host: /
    username:
    password:
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  data:
    mongodb:
      host:
      database:
      port: 27017
      username:
      password:
      authentication-database: admin
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  elasticsearch:
    uris:
mybatis-plus:
  type-aliases-package: com.leaf.entity # 别名扫描包
logging:
  level:
    com.leaf: debug
